In [4]:
import tensorflow as tf 
import numpy as np 
a=np.random.rand(2,3,4)
print(a)
a=np.arange(10)


[[[0.2372057  0.02193459 0.23353323 0.2408018 ]
  [0.19306112 0.84695253 0.6623324  0.27048639]
  [0.49115196 0.70019966 0.12135076 0.22968241]]

 [[0.12587253 0.77833952 0.28367302 0.8494922 ]
  [0.6618859  0.57734921 0.90988972 0.66032268]
  [0.99083049 0.90854447 0.19325916 0.47027665]]]


TypeError: random_shuffle() got an unexpected keyword argument 'axis'